source 'git@git.superid.cn:iOS/SISpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

use_frameworks!

target 'SIUtils_Example' do
  pod 'SIUtils', :path => '../'

  target 'SIUtils_Tests' do
    inherit! :search_paths

    
  end
end
